### PR TITLE
Remove composer test and add phpunit

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by iansltx** [comment]
Question is whether, when testing, you're more likely to have composer globally installed or phpunit globally installed. See here:

https://github.com/thephpleague/skeleton/issues/21

and here:

https://github.com/thephpleague/skeleton/pull/7

This also means that when additional test runners are added (e.g. humbug) you have to add a test runner script or the like.

Open to discussion though.

**Comment by harikt** [comment]
Personally I have phpunit.phar in my `/usr/bin` . Same for testing tools either download the source and point to the bin.

I have very limited bandwidth and I do believe there are many people who don't have the fastest internet. Some people though argue that you can do composer install --no-dev or is installing from cache etc .

I hate those arguments :) .

**Comment by iansltx** [comment]
Taking that point to its logical conclusion, you'd want to remove phpunit as a dev dependency from composer.json entirely. I know you've mentioned doing exactly this elsewhere but in the interest of expedient defaults (e.g. using composer require rather than editing the json file directly, as well as in this case...and using composer at all) I'd rather document the case that assumes the least (having composer, and only composer, installed). For cases like yours, you're already familiar with the workaround of cloning and using PHPUnit manually.

If someone else brings this same situation up, I'll revisit this.For now, I'd like to keep things as-is.

**Comment by harikt** [comment]
> Taking that point to its logical conclusion, you'd want to remove phpunit as a dev dependency from composer.json entirely

I didn't said that ;) . Nor is in this PR.

Apart from that I am ok with. :) .

**Pull request closed without merging**
